version: '3.7'

services:
  nginx:
    image: nginx:1.15
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - flask
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask
    command: gunicorn --bind 0.0.0.0:8000 app:app
    volumes:
      - ./:/var/www
    networks:
      my-network:
        aliases:
          - chat-app

networks:
  my-network: